### ISSUE TITLE
Sync not considering all properties

### ISSUE THREAD

**Issue by mbassett** [Icinga/icingaweb2-module-aws#7] opened 2016-11-02 18:54 UTC
Sync says there are no changes, even when properties of the data has changed.

To reproduce:

Use EC2 instance import w/ instance state
(see pull request)

Set sync property to set host['disable']  to  1  when state!=running
Sync
nodes in non running state should now be disabled

remove sync property  or   even change it to set host['disable'] to 0 and try and re-run the sync
it will say there are no changes. 

It only seems to note/allow sync changes if the EC2 import source changes

**Comment by mbassett** [comment] 2016-11-02 20:40
Also, when an instance transitions state from running to terminated or suspended it does not seem to trigger an update to disable the instance (yes i am running a new import), it only goes into effect once it disappears completely from EC2 inventory, and then i get a delete host in the sync.

**Comment by N-o-X** [comment] 2019-08-12 14:58
Hey @mbassett, if you're still using this module nearly 3 years later, does this problem still occur? I could not reproduce this on my system. Might have been fixed with a Director update some time ago.

**Closed as completed** 2019-08-13 07:29 UTC
